version: '3'

services:
  app:
    image: tp-bioinformatica
    container_name: tp-bioinformatica
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./Ejercicios:/opt/Ejercicios